version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    expose:
      - 80
    depends_on:
      - qa

  qa:
    build:
      context: ./services/qa
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${SDC_DB}

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - qa
      - client
