version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3009:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_QA_API=http://localhost:5001

  qa:
    container_name: qa
    build:
      context: ./services/questions-answers
      dockerfile: Dockerfile
    volumes:
      - "./services/qa:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5001:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SDC_DATABASE_URL=postgres://postgres:postgres@qa-db:54321/qa
    depends_on:
      - qa-db

  qa-db:
    container_name: qa-db
    image: postgres:latest
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - client
      - qa
