version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_QA_API_URL=http://localhost:5001

  qa:
    container_name: qa
    build:
      context: ./services/qa
      dockerfile: Dockerfile
    volumes:
      - "./services/qa:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5001:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://sdcpostgres:sdcpostgres@qa-db:5432/qa_dev
      - DATABASE_TEST_URL=postgres://sdcpostgres:sdcpostgres@qa-db:5432/qa_test
    depends_on:
      - qa-db

  qa-db:
    container_name: qa-db
    build:
      context: ./services/qa/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=sdcpostgres
      - POSTGRES_PASSWORD=sdcpostgres

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - client
      - qa
