version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
    args:
      - NODE_ENV=production
      - REACT_APP_QA_API_URL=${REACT_APP_QA_API_URL}
    expose:
      - 80
    depends_on:
      - qa

  qa:
    container_name: qa
    build:
      context: ./services/qa
      dockerfile: Dockerfile-stage
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://sdcposrgres:sdcpostgres@qa-db:5432/qa_stage
      - DATABASE_TEST_URL=postgres://sdcpostgres:sdcpostgres@qa-db:5432/qa_test
    expose:
      - 5000
    depends_on:
      - qa-db

  qa-db:
    container_name: qa-db
    build:
      context: ./services/qa/db
      dockerfile: Dockerfile-stage
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sdcpostgres
      - POSTGRES_PASSWORD=sdcpostgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - qa
      - client
