version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3009:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_QA_API=$REACT_APP_QA_API

  qa:
    container_name: qa
    build:
      context: ./services/qa
      dockerfile: Dockerfile
    volumes:
      - "./services/qa:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 5001:5000
    environment:
      - NODE_ENV=development
      - PORT=5009
      - REDIS_PORT=6379
      - DB_HOST=$SDC_DB
    depends_on:
      - qa-db

  qa-db:
    container_name: qa-db
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qa
